---

- include_tasks: install.yaml

- name: Setup etcd service file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  become: yes

- name: Start etcd service
  service:
     name: etcd
     state: started
     enabled: yes
     daemon_reload: yes
  become: yes
