---
- name: Make installation directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
with_items:
    - /etc/cni/net.d
    - /opt/cni/bin
    - /var/lib/kubelet
    - /var/lib/kube-proxy
    - /var/lib/kubernetes
    - /var/run/kubernetes
    - /etc/containerd/

- name: Update install packages
  apt:
    name: "{{item}}"
  with_items:
    - socat
    - conntrack
    - ipset

- name: Fetch Vault archive
  get_url:
    url: "{{item}}"
    dest: /tmp/{{ item }}
    force: yes
  with_items:
    - https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.12.0/crictl-v1.12.0-linux-amd64.tar.gz 
    - https://storage.googleapis.com/kubernetes-the-hard-way/runsc-50c283b9f56bb7200938d9e207355f05f79f0d17 
    - https://github.com/opencontainers/runc/releases/download/v1.0.0-rc5/runc.amd64 
    - https://github.com/containernetworking/plugins/releases/download/v0.6.0/cni-plugins-amd64-v0.6.0.tg
    - https://github.com/containerd/containerd/releases/download/v1.2.0-rc.0/containerd-1.2.0-rc.0.linux-amd64.tar.gz 
    - https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kube-proxy
    - https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubelet

- name: Move kube-proxy kubelet
  file:
    src: /var/lib/{{item}}
    dest: /usr/local/bin/{{item}}
    mode: 0755
  with_items:
    - kubelet 
    - kube-proxy  

- name: Move runsc
  file:
    src: tmp/https://storage.googleapis.com/kubernetes-the-hard-way/runsc-50c283b9f56bb7200938d9e207355f05f79f0d17 
    dest: /usr/local/bin/runsc
    state: hard
    mode: 0111

- name: Move runc
  file: 
    src: tmp/https://github.com/opencontainers/runc/releases/download/v1.0.0-rc5/runc.amd64 
    dest: usr/local/bin/runc  
    state: hard
    mode: 0111

- name: Extract crictl binary
  unarchive:
    src: /tmp/https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.12.0/crictl-v1.12.0-linux-amd64.tar.gz 
    dest: /usr/local/bin
  remote_src: yes

- name: Extract cni-plugins binary
  unarchive:
    src: /tmp/https://github.com/containernetworking/plugins/releases/download/v0.6.0/cni-plugins-amd64-v0.6.0.tgz
    dest: /opt/cni/bin 
  remote_src: yes

- name: Extract containerd binary
  unarchive:
    src: /tmp/https://github.com/containerd/containerd/releases/download/v1.2.0-rc.0/containerd-1.2.0-rc.0.linux-amd64.tar.gz
    dest:
  remote_src: yes

- name: Configure CNI networking
  file: 
    src: 10-bridge.conf.j2
    dest: /etc/cni/net.d/10-bridge.conf

- name: Containerd config file
  file: 
    src: config.toml.j2
    dest: /etc/containerd/config.toml

- name: Containerd service file
  file: 
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service

- name: Kubelet-config file
  file:
    src: kublet-config.yaml.j2
    dest:/var/lib/kubelet/kubelet-config.yaml

- name: Kubelet key.pem files
  file:
    src: {{item}}.pem.yaml.j2
    dest: /var/lib/kubelet/{{item}}.pem.yaml
  with_item: 
    - {{HOSTNAME}}-key
    - {{HOSTNAME}}

- name: File ca.pem 
  file:
    src: ca.pem.j2
    dest: /var/lib/kubernetes/ca.pem

- name: Kubelet.service file
  file:
    src: kublet.service.j2
    dest:/var/lib/kubelet/kubelet-config.yaml

- name: Kube-proxy.kubeconfig file
  file:
    src: kubecongfig.j2
    dest: /var/lib/kube-proxy/kubeconfig

- name: Kube-proxy-config file
  file:
    src: kube-proxy-config.yaml.j2
    dest: /var/lib/kube-proxy/kube-proxy-config.yaml

- name: Kube-proxy.service file
  file:
    src: kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service

- name: Enable worker services
  systemd:
    name: "{{ item }}"
    enabled: no
    daemon_reload: yes
   with_items:
    - containerd
    - kubelet
    - kube-proxy

